# Generated by Django 5.2.4 on 2025-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_images',
            new_name='PostImages',
        ),
        migrations.RenameModel(
            old_name='user_table',
            new_name='UserTable',
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
