# Generated by Django 5.2.4 on 2025-07-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
                ('player_runs', models.IntegerField(default=0)),
                ('player_wickets', models.IntegerField(default=0)),
                ('player_hundreds', models.IntegerField(default=0)),
                ('player_fifties', models.IntegerField(default=0)),
                ('player_jersey_no', models.IntegerField(unique=True)),
                ('player_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.playercategory')),
                ('player_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.playerteam')),
            ],
        ),
    ]
