# Generated by Django 5.2.4 on 2025-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(choices=[('python', 'Python'), ('flutter', 'Flutter'), ('django', 'Django'), ('react', 'React'), ('php', 'PHP')], max_length=100)),
                ('course_code', models.CharField(max_length=50, verbose_name='Course Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(verbose_name='Course Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('development', 'Development'), ('hr', 'HR')], max_length=50)),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('linkedin_url', models.URLField(verbose_name='LinkedIn Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateOfBirth', models.DateField(verbose_name='Birth Date')),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
