# Generated by Django 5.2.4 on 2025-07-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='actor_pics/')),
                ('bio', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
                ('awards', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')])),
                ('birth_date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='director_pics/')),
                ('bio', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
                ('awards', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('trailer_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.actor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.state'),
        ),
        migrations.AddField(
            model_name='actor',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.state'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='user_pics/')),
                ('phone', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.state')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.user')),
            ],
        ),
    ]
