# Generated by Django 5.2.4 on 2025-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_type', models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('business', 'Business')], max_length=100)),
                ('news_desc', models.TextField()),
                ('news_date', models.DateField()),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('news_tags', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
